// Writes the SQL that brings the database's programmes, streams and chapters in line with
// supabase/curriculum/maths.json (DECISIONS.md, D-094). Run it when the curriculum file changes,
// and put its output in a new migration:
//
//   node scripts/curriculum-sql.mjs > supabase/migrations/<version>_curriculum.sql
//
// Every statement is an upsert keyed on codes and slugs: a chapter keeps its id, so its
// lessons and exercises stay attached, and a stream keeps its code, so its students stay.

import { readFileSync } from "node:fs";

const curriculum = JSON.parse(
  readFileSync(new URL("../supabase/curriculum/maths.json", import.meta.url), "utf8"),
);

const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;

const programmes = [];
const levels = [];
const chapters = [];
let levelPosition = 0;

curriculum.programmes.forEach((programme, programmeIndex) => {
  programmes.push(
    `  (${quote(programme.code)}, ${quote(programme.slug)}, ${quote(programme.label)}, ${quote(programme.cycle)}, ${(programmeIndex + 1) * 10})`,
  );
  for (const level of programme.levels) {
    levelPosition += 10;
    levels.push(
      `  (${quote(level.code)}, ${quote(level.label)}, ${quote(programme.cycle)}, ${levelPosition}, ${quote(programme.code)})`,
    );
  }
  programme.chapters.forEach(([semester, slug, title], index) => {
    chapters.push(
      `  (${quote(programme.code)}, ${quote(slug)}, ${quote(title)}, ${semester}, ${index + 1})`,
    );
  });
});

process.stdout
  .write(`-- Generated by scripts/curriculum-sql.mjs from supabase/curriculum/maths.json.

insert into public.programmes (code, slug, label, cycle, position) values
${programmes.join(",\n")}
on conflict (code) do update set
  slug = excluded.slug,
  label = excluded.label,
  cycle = excluded.cycle,
  position = excluded.position;

-- Positions are unique: moved out of the way first, so the new order can be written in any
-- sequence.
update public.levels set position = position + 10000;

insert into public.levels (code, label, cycle, position, programme_code) values
${levels.join(",\n")}
on conflict (code) do update set
  label = excluded.label,
  cycle = excluded.cycle,
  position = excluded.position,
  programme_code = excluded.programme_code;

-- A chapter made before programmes existed follows its level's programme, so the upsert
-- below finds it by its slug instead of adding a second one.
update public.chapters c
set programme_code = l.programme_code
from public.levels l
where c.programme_code is null
  and l.code = c.level_code;

insert into public.chapters (programme_code, slug, title, semester, position) values
${chapters.join(",\n")}
on conflict (programme_code, slug) do update set
  title = excluded.title,
  semester = excluded.semester,
  position = excluded.position;
`);
