-- Maths programmes (DECISIONS.md, D-094).
--
-- A stream (« filière ») is what a student is in: 2e bac PC, SVT, STE… A programme is the maths
-- syllabus several streams share: PC, SVT, Agro, STE and STM all follow « 2e bac Sciences
-- expérimentales et technologiques ». Chapters, and so lessons and exercises, belong to the
-- programme, so each is written once; a student reads her stream's programme.
--
-- Adds the streams the brief left out (tronc commun technologique and lettres, 1re bac STE,
-- STM and lettres, 2e bac Agro, STE, STM, gestion comptable, lettres, sciences humaines) and
-- every chapter of the official programmes, by semester (supabase/curriculum/maths.json).
--
-- chapters.level_code is kept for now, nullable and no longer read: dropping it is left for
-- a later migration, once the owner has agreed.

create table public.programmes (
  code text primary key check (code ~ '^[0-9A-Z-]{2,16}$'),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  label text not null check (char_length(label) between 1 and 80),
  cycle text not null check (cycle in ('college', 'tronc_commun', '1bac', '2bac')),
  position smallint not null
);

alter table public.programmes enable row level security;

-- A table of contents, as chapters are; written by migrations only.
create policy "programmes: select everyone"
  on public.programmes for select to anon, authenticated
  using (true);

alter table public.levels
  add column programme_code text references public.programmes (code) on update cascade;

alter table public.chapters
  add column programme_code text references public.programmes (code) on update cascade,
  add column semester smallint check (semester in (1, 2)),
  add constraint chapters_programme_slug_key unique (programme_code, slug);

-- New chapters have no level: the column is no longer read.
alter table public.chapters alter column level_code drop not null;

-- Generated by scripts/curriculum-sql.mjs from supabase/curriculum/maths.json.

insert into public.programmes (code, slug, label, cycle, position) values
  ('1AC', '1ac', '1re année collège', 'college', 10),
  ('2AC', '2ac', '2e année collège', 'college', 20),
  ('3AC', '3ac', '3e année collège', 'college', 30),
  ('TC-ST', 'tronc-commun-sciences', 'Tronc commun scientifique et technologique', 'tronc_commun', 40),
  ('TC-LSH', 'tronc-commun-lettres', 'Tronc commun Lettres et sciences humaines', 'tronc_commun', 50),
  ('1BAC-SM', '1bac-sciences-maths', '1re bac Sciences mathématiques', '1bac', 60),
  ('1BAC-SEXP', '1bac-sciences-experimentales', '1re bac Sciences expérimentales et technologiques', '1bac', 70),
  ('1BAC-ECO', '1bac-economie', '1re bac Sciences économiques et gestion', '1bac', 80),
  ('1BAC-LSH', '1bac-lettres', '1re bac Lettres et sciences humaines', '1bac', 90),
  ('2BAC-SM', '2bac-sciences-maths', '2e bac Sciences mathématiques', '2bac', 100),
  ('2BAC-SEXP', '2bac-sciences-experimentales', '2e bac Sciences expérimentales et technologiques', '2bac', 110),
  ('2BAC-ECO', '2bac-economie', '2e bac Sciences économiques et gestion', '2bac', 120),
  ('2BAC-LSH', '2bac-lettres', '2e bac Lettres et sciences humaines', '2bac', 130)
on conflict (code) do update set
  slug = excluded.slug,
  label = excluded.label,
  cycle = excluded.cycle,
  position = excluded.position;

-- Positions are unique: moved out of the way first, so the new order can be written in any
-- sequence.
update public.levels set position = position + 10000;

insert into public.levels (code, label, cycle, position, programme_code) values
  ('1AC', '1re année collège', 'college', 10, '1AC'),
  ('2AC', '2e année collège', 'college', 20, '2AC'),
  ('3AC', '3e année collège', 'college', 30, '3AC'),
  ('TC', 'Tronc commun Sciences', 'tronc_commun', 40, 'TC-ST'),
  ('TC-TECH', 'Tronc commun Technologique', 'tronc_commun', 50, 'TC-ST'),
  ('TC-LSH', 'Tronc commun Lettres et sciences humaines', 'tronc_commun', 60, 'TC-LSH'),
  ('1BAC-SM', '1re bac Sciences mathématiques', '1bac', 70, '1BAC-SM'),
  ('1BAC-SE', '1re bac Sciences expérimentales', '1bac', 80, '1BAC-SEXP'),
  ('1BAC-SVT', '1re bac SVT', '1bac', 90, '1BAC-SEXP'),
  ('1BAC-STE', '1re bac Sciences et technologies électriques', '1bac', 100, '1BAC-SEXP'),
  ('1BAC-STM', '1re bac Sciences et technologies mécaniques', '1bac', 110, '1BAC-SEXP'),
  ('1BAC-ECO', '1re bac Sciences économiques et gestion', '1bac', 120, '1BAC-ECO'),
  ('1BAC-LSH', '1re bac Lettres et sciences humaines', '1bac', 130, '1BAC-LSH'),
  ('2BAC-SMA', '2e bac Sciences mathématiques A', '2bac', 140, '2BAC-SM'),
  ('2BAC-SMB', '2e bac Sciences mathématiques B', '2bac', 150, '2BAC-SM'),
  ('2BAC-PC', '2e bac Sciences physiques', '2bac', 160, '2BAC-SEXP'),
  ('2BAC-SVT', '2e bac SVT', '2bac', 170, '2BAC-SEXP'),
  ('2BAC-SAGRO', '2e bac Sciences agronomiques', '2bac', 180, '2BAC-SEXP'),
  ('2BAC-STE', '2e bac Sciences et technologies électriques', '2bac', 190, '2BAC-SEXP'),
  ('2BAC-STM', '2e bac Sciences et technologies mécaniques', '2bac', 200, '2BAC-SEXP'),
  ('2BAC-ECO', '2e bac Sciences économiques', '2bac', 210, '2BAC-ECO'),
  ('2BAC-SGC', '2e bac Sciences de gestion comptable', '2bac', 220, '2BAC-ECO'),
  ('2BAC-LET', '2e bac Lettres', '2bac', 230, '2BAC-LSH'),
  ('2BAC-SH', '2e bac Sciences humaines', '2bac', 240, '2BAC-LSH')
on conflict (code) do update set
  label = excluded.label,
  cycle = excluded.cycle,
  position = excluded.position,
  programme_code = excluded.programme_code;

-- A chapter made before programmes existed follows its level's programme, so the upsert
-- below finds it by its slug instead of adding a second one.
update public.chapters c
set programme_code = l.programme_code
from public.levels l
where c.programme_code is null
  and l.code = c.level_code;

insert into public.chapters (programme_code, slug, title, semester, position) values
  ('1AC', 'operations-entiers-decimaux', 'Opérations sur les nombres entiers et décimaux', 1, 1),
  ('1AC', 'ecriture-fractionnaire', 'Nombres en écriture fractionnaire', 1, 2),
  ('1AC', 'operations-ecriture-fractionnaire', 'Opérations sur les nombres en écriture fractionnaire', 1, 3),
  ('1AC', 'notions-de-base-geometrie', 'Notions de base de la géométrie dans le plan', 1, 4),
  ('1AC', 'inegalite-triangulaire-mediatrice', 'Inégalité triangulaire et médiatrice d''un segment', 1, 5),
  ('1AC', 'angles', 'Angles', 1, 6),
  ('1AC', 'nombres-relatifs', 'Nombres relatifs : présentation et comparaison', 1, 7),
  ('1AC', 'relatifs-addition-soustraction', 'Nombres relatifs : addition et soustraction', 1, 8),
  ('1AC', 'relatifs-multiplication-division', 'Nombres relatifs : multiplication et division', 1, 9),
  ('1AC', 'puissances', 'Puissances', 1, 10),
  ('1AC', 'triangles', 'Triangles', 2, 11),
  ('1AC', 'bissectrice-hauteur', 'Bissectrice et hauteur d''un triangle', 2, 12),
  ('1AC', 'developpement-factorisation', 'Développement et factorisation', 2, 13),
  ('1AC', 'symetrie-centrale', 'Symétrie centrale', 2, 14),
  ('1AC', 'equations', 'Équations', 2, 15),
  ('1AC', 'parallelogramme', 'Parallélogramme', 2, 16),
  ('1AC', 'quadrilateres-particuliers', 'Quadrilatères particuliers', 2, 17),
  ('1AC', 'angles-paralleles-secante', 'Angles formés par deux droites parallèles et une sécante', 2, 18),
  ('1AC', 'droite-graduee-reperage', 'Droite graduée et repérage dans le plan', 2, 19),
  ('1AC', 'cercle', 'Cercle', 2, 20),
  ('1AC', 'proportionnalite', 'Proportionnalité', 2, 21),
  ('1AC', 'statistiques', 'Statistiques', 2, 22),
  ('1AC', 'prisme-cylindre', 'Prisme droit et cylindre de révolution', 2, 23),
  ('2AC', 'operations-nombres-relatifs', 'Opérations sur les nombres relatifs', 1, 1),
  ('2AC', 'nombres-rationnels', 'Les nombres rationnels', 1, 2),
  ('2AC', 'rationnels-addition-soustraction', 'Nombres rationnels : addition et soustraction', 1, 3),
  ('2AC', 'symetrie-axiale', 'Symétrie axiale', 1, 4),
  ('2AC', 'rationnels-multiplication-division', 'Nombres rationnels : multiplication et division', 1, 5),
  ('2AC', 'triangle-droites-paralleles', 'Triangle et droites parallèles', 1, 6),
  ('2AC', 'quatre-operations-rationnels', 'Les quatre opérations sur les nombres rationnels', 1, 7),
  ('2AC', 'puissances', 'Puissances', 1, 8),
  ('2AC', 'droites-remarquables', 'Droites remarquables d''un triangle', 1, 9),
  ('2AC', 'calcul-litteral', 'Calcul littéral', 2, 10),
  ('2AC', 'triangle-rectangle-cercle', 'Triangle rectangle et cercle', 2, 11),
  ('2AC', 'pythagore-cosinus', 'Théorème de Pythagore et cosinus d''un angle aigu', 2, 12),
  ('2AC', 'equations', 'Équations', 2, 13),
  ('2AC', 'vecteurs-translation', 'Vecteurs et translation', 2, 14),
  ('2AC', 'ordre-operations', 'Ordre et opérations', 2, 15),
  ('2AC', 'proportionnalite', 'Proportionnalité', 2, 16),
  ('2AC', 'statistiques', 'Statistiques', 2, 17),
  ('2AC', 'prisme-pyramide-cone', 'Prisme droit, pyramide et cône de révolution', 2, 18),
  ('3AC', 'developpement-factorisation', 'Développement, factorisation et identités remarquables', 1, 1),
  ('3AC', 'puissances', 'Puissances', 1, 2),
  ('3AC', 'racines-carrees', 'Racines carrées', 1, 3),
  ('3AC', 'theoreme-de-thales', 'Théorème de Thalès', 1, 4),
  ('3AC', 'theoreme-de-pythagore', 'Théorème de Pythagore', 1, 5),
  ('3AC', 'ordre-operations', 'Ordre et opérations', 1, 6),
  ('3AC', 'trigonometrie', 'Triangle rectangle et trigonométrie', 1, 7),
  ('3AC', 'angles-inscrits', 'Angles inscrits et angles au centre', 1, 8),
  ('3AC', 'triangles-isometriques-semblables', 'Triangles isométriques et triangles semblables', 1, 9),
  ('3AC', 'equations-et-inequations', 'Équations et inéquations du premier degré à une inconnue', 2, 10),
  ('3AC', 'vecteurs-translation', 'Vecteurs et translation', 2, 11),
  ('3AC', 'repere-plan', 'Repère dans le plan', 2, 12),
  ('3AC', 'equation-droite', 'Équation d''une droite', 2, 13),
  ('3AC', 'fonctions-lineaire-affine', 'Fonction linéaire et fonction affine', 2, 14),
  ('3AC', 'systemes', 'Systèmes de deux équations à deux inconnues', 2, 15),
  ('3AC', 'geometrie-espace', 'Géométrie dans l''espace', 2, 16),
  ('3AC', 'statistiques', 'Statistiques', 2, 17),
  ('TC-ST', 'ensembles-de-nombres', 'Les ensembles de nombres ℕ, ℤ, 𝔻, ℚ et ℝ', 1, 1),
  ('TC-ST', 'arithmetique', 'Arithmétique dans ℕ', 1, 2),
  ('TC-ST', 'calcul-vectoriel', 'Calcul vectoriel dans le plan', 1, 3),
  ('TC-ST', 'projection', 'La projection dans le plan', 1, 4),
  ('TC-ST', 'ordre', 'L''ordre dans ℝ', 1, 5),
  ('TC-ST', 'droite', 'La droite dans le plan', 1, 6),
  ('TC-ST', 'polynomes', 'Les polynômes', 1, 7),
  ('TC-ST', 'equations-inequations-systemes', 'Équations, inéquations et systèmes', 1, 8),
  ('TC-ST', 'trigonometrie', 'Trigonométrie : règles du calcul trigonométrique', 1, 9),
  ('TC-ST', 'equations-trigonometriques', 'Trigonométrie : équations et inéquations trigonométriques', 2, 10),
  ('TC-ST', 'generalites-fonctions', 'Généralités sur les fonctions', 2, 11),
  ('TC-ST', 'transformations', 'Transformations du plan', 2, 12),
  ('TC-ST', 'produit-scalaire', 'Le produit scalaire', 2, 13),
  ('TC-ST', 'geometrie-espace', 'Géométrie dans l''espace', 2, 14),
  ('TC-ST', 'statistiques', 'Statistiques', 2, 15),
  ('TC-LSH', 'operations-reels', 'Opérations dans ℝ', 1, 1),
  ('TC-LSH', 'ordre', 'L''ordre dans ℝ', 1, 2),
  ('TC-LSH', 'equations-inequations-systemes', 'Équations, inéquations et systèmes', 1, 3),
  ('TC-LSH', 'statistiques', 'Statistiques', 1, 4),
  ('TC-LSH', 'fonctions', 'Fonctions numériques', 2, 5),
  ('TC-LSH', 'repere', 'Le repère dans le plan', 2, 6),
  ('TC-LSH', 'droite', 'La droite dans le plan', 2, 7),
  ('1BAC-SM', 'logique', 'Logique mathématique', 1, 1),
  ('1BAC-SM', 'ensembles-applications', 'Ensembles et applications', 1, 2),
  ('1BAC-SM', 'generalites-fonctions', 'Généralités sur les fonctions', 1, 3),
  ('1BAC-SM', 'barycentre', 'Le barycentre dans le plan', 1, 4),
  ('1BAC-SM', 'produit-scalaire', 'Le produit scalaire dans le plan', 1, 5),
  ('1BAC-SM', 'trigonometrie', 'Calcul trigonométrique', 1, 6),
  ('1BAC-SM', 'suites', 'Les suites numériques', 1, 7),
  ('1BAC-SM', 'limites', 'Limites d''une fonction', 1, 8),
  ('1BAC-SM', 'rotation', 'La rotation dans le plan', 1, 9),
  ('1BAC-SM', 'derivation', 'La dérivation', 2, 10),
  ('1BAC-SM', 'etude-fonctions', 'Étude des fonctions', 2, 11),
  ('1BAC-SM', 'vecteurs-espace', 'Vecteurs de l''espace', 2, 12),
  ('1BAC-SM', 'geometrie-espace', 'Géométrie analytique de l''espace', 2, 13),
  ('1BAC-SM', 'denombrement', 'Dénombrement', 2, 14),
  ('1BAC-SM', 'produit-scalaire-espace', 'Le produit scalaire dans l''espace', 2, 15),
  ('1BAC-SM', 'arithmetique', 'Arithmétique dans ℤ', 2, 16),
  ('1BAC-SM', 'produit-vectoriel', 'Le produit vectoriel', 2, 17),
  ('1BAC-SEXP', 'logique', 'Notions de logique', 1, 1),
  ('1BAC-SEXP', 'generalites-fonctions', 'Généralités sur les fonctions', 1, 2),
  ('1BAC-SEXP', 'barycentre', 'Le barycentre dans le plan', 1, 3),
  ('1BAC-SEXP', 'produit-scalaire', 'Le produit scalaire dans le plan', 1, 4),
  ('1BAC-SEXP', 'suites', 'Les suites numériques', 1, 5),
  ('1BAC-SEXP', 'trigonometrie', 'Calcul trigonométrique', 1, 6),
  ('1BAC-SEXP', 'rotation', 'La rotation dans le plan', 2, 7),
  ('1BAC-SEXP', 'limites', 'Limites d''une fonction numérique', 2, 8),
  ('1BAC-SEXP', 'derivation', 'Dérivation d''une fonction numérique', 2, 9),
  ('1BAC-SEXP', 'etude-fonctions', 'Représentation graphique d''une fonction', 2, 10),
  ('1BAC-SEXP', 'vecteurs-espace', 'Vecteurs de l''espace', 2, 11),
  ('1BAC-SEXP', 'geometrie-espace', 'Géométrie analytique de l''espace', 2, 12),
  ('1BAC-ECO', 'logique', 'Notions de logique', 1, 1),
  ('1BAC-ECO', 'equations-inequations-systemes', 'Équations, inéquations et systèmes', 1, 2),
  ('1BAC-ECO', 'generalites-fonctions', 'Généralités sur les fonctions numériques', 1, 3),
  ('1BAC-ECO', 'suites', 'Les suites numériques', 1, 4),
  ('1BAC-ECO', 'denombrement', 'Dénombrement', 1, 5),
  ('1BAC-ECO', 'logarithme-decimal', 'Le logarithme décimal', 2, 6),
  ('1BAC-ECO', 'limites', 'Limites d''une fonction', 2, 7),
  ('1BAC-ECO', 'derivation', 'La dérivation', 2, 8),
  ('1BAC-ECO', 'etude-fonctions', 'Étude et représentation graphique des fonctions', 2, 9),
  ('1BAC-ECO', 'barycentre', 'Le barycentre', 2, 10),
  ('1BAC-LSH', 'logique', 'Notions de logique', 1, 1),
  ('1BAC-LSH', 'calcul-numerique', 'Calcul numérique : proportionnalité et pourcentages', 1, 2),
  ('1BAC-LSH', 'generalites-fonctions', 'Généralités sur les fonctions numériques', 1, 3),
  ('1BAC-LSH', 'suites', 'Les suites numériques', 1, 4),
  ('1BAC-LSH', 'denombrement', 'Dénombrement', 2, 5),
  ('1BAC-LSH', 'limites', 'Limite d''une fonction numérique', 2, 6),
  ('1BAC-LSH', 'derivation', 'La dérivation', 2, 7),
  ('1BAC-LSH', 'etude-fonctions', 'Étude et représentation des fonctions numériques', 2, 8),
  ('2BAC-SM', 'limites-et-continuite', 'Limites et continuité', 1, 1),
  ('2BAC-SM', 'derivation', 'Dérivation et étude des fonctions', 1, 2),
  ('2BAC-SM', 'accroissements-finis', 'Théorème des accroissements finis', 1, 3),
  ('2BAC-SM', 'suites-numeriques', 'Suites numériques', 1, 4),
  ('2BAC-SM', 'logarithmes', 'Fonctions logarithmiques', 1, 5),
  ('2BAC-SM', 'exponentielles', 'Fonctions exponentielles', 1, 6),
  ('2BAC-SM', 'equations-differentielles', 'Équations différentielles', 1, 7),
  ('2BAC-SM', 'nombres-complexes', 'Nombres complexes (1re partie)', 1, 8),
  ('2BAC-SM', 'primitives-integrales', 'Fonctions primitives et calcul intégral', 2, 9),
  ('2BAC-SM', 'nombres-complexes-2', 'Nombres complexes (2e partie)', 2, 10),
  ('2BAC-SM', 'arithmetique', 'Arithmétique dans ℤ', 2, 11),
  ('2BAC-SM', 'structures-algebriques', 'Structures algébriques', 2, 12),
  ('2BAC-SM', 'probabilites', 'Dénombrement et probabilités', 2, 13),
  ('2BAC-SM', 'espaces-vectoriels', 'Espaces vectoriels', 2, 14),
  ('2BAC-SEXP', 'limites-et-continuite', 'Limites et continuité', 1, 1),
  ('2BAC-SEXP', 'derivation', 'Dérivation et étude des fonctions', 1, 2),
  ('2BAC-SEXP', 'suites-numeriques', 'Suites numériques', 1, 3),
  ('2BAC-SEXP', 'primitives', 'Fonctions primitives', 1, 4),
  ('2BAC-SEXP', 'logarithmes', 'Fonctions logarithmiques', 1, 5),
  ('2BAC-SEXP', 'nombres-complexes', 'Nombres complexes (1re partie)', 1, 6),
  ('2BAC-SEXP', 'exponentielles', 'Fonctions exponentielles', 2, 7),
  ('2BAC-SEXP', 'nombres-complexes-2', 'Nombres complexes (2e partie)', 2, 8),
  ('2BAC-SEXP', 'calcul-integral', 'Calcul intégral', 2, 9),
  ('2BAC-SEXP', 'equations-differentielles', 'Équations différentielles', 2, 10),
  ('2BAC-SEXP', 'geometrie-espace', 'Géométrie dans l''espace : produit scalaire et produit vectoriel', 2, 11),
  ('2BAC-SEXP', 'probabilites', 'Dénombrement et probabilités', 2, 12),
  ('2BAC-ECO', 'limites-et-continuite', 'Limites et continuité', 1, 1),
  ('2BAC-ECO', 'derivation', 'Dérivation et étude des fonctions', 1, 2),
  ('2BAC-ECO', 'suites-numeriques', 'Suites numériques', 1, 3),
  ('2BAC-ECO', 'logarithmes', 'Fonctions logarithmiques', 1, 4),
  ('2BAC-ECO', 'exponentielles', 'Fonctions exponentielles', 2, 5),
  ('2BAC-ECO', 'primitives-integrales', 'Fonctions primitives et calcul intégral', 2, 6),
  ('2BAC-ECO', 'probabilites', 'Dénombrement et probabilités', 2, 7),
  ('2BAC-LSH', 'suites-numeriques', 'Suites numériques', 1, 1),
  ('2BAC-LSH', 'limite-suite', 'Limite d''une suite', 1, 2),
  ('2BAC-LSH', 'derivation', 'Dérivation et étude des fonctions', 1, 3),
  ('2BAC-LSH', 'logarithmes', 'Fonctions logarithmiques', 1, 4),
  ('2BAC-LSH', 'exponentielles', 'Fonctions exponentielles', 2, 5),
  ('2BAC-LSH', 'probabilites', 'Probabilités', 2, 6)
on conflict (programme_code, slug) do update set
  title = excluded.title,
  semester = excluded.semester,
  position = excluded.position;

alter table public.levels alter column programme_code set not null;
alter table public.chapters alter column programme_code set not null;

create index levels_programme_idx on public.levels (programme_code);
create index chapters_programme_position_idx on public.chapters (programme_code, semester, position);

-- The programme a student reads: her stream's. Only while she is active or paused, as her
-- level was (D-060).
create function private.my_programme()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select l.programme_code
  from public.levels l
  where l.code = (select private.my_level());
$$;

-- « enrolled » lessons are her programme's, where they were her level's.
create or replace function private.lesson_visible_to_me(
  p_lesson_id uuid,
  p_chapter_id uuid,
  p_status public.publication_status,
  p_visibility public.lesson_visibility
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $function$
  select
    (p_status = 'published' and p_visibility = 'public')
    or (select private.is_tutor())
    or (
      p_status = 'published'
      and p_visibility = 'enrolled'
      and exists (
        select 1
        from public.chapters c
        where c.id = p_chapter_id
          and c.programme_code = (select private.my_programme())
      )
    )
    or (
      p_status = 'published'
      and p_visibility = 'specific'
      and (select private.my_student_status()) in ('actif', 'en_pause')
      and exists (
        select 1
        from public.lesson_access la
        where la.lesson_id = p_lesson_id
          and la.student_id = (select auth.uid())
      )
    );
$function$;

revoke execute on all functions in schema private from public;
grant execute on all functions in schema private to anon, authenticated, service_role;
